version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - 'Dependencies'
      - 'For Uncommitted Issue'
    ignore:
      - dependency-name: p-wait-for
        update-types: [version-update:semver-major]
      - dependency-name: '@types/vscode'
        update-types: [version-update:semver-minor]
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'Dependencies'
      - 'For Uncommitted Issue'
