version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - 'pr: dependencies'
    groups:
      jest:
        patterns: ['jest', 'jest-runner-vscode', 'ts-jest', '@types/jest']
      eslint:
        patterns: ['eslint', 'eslint-config-*', '@typescript-eslint/*', '@types/eslint']
    ignore:
      - dependency-name: p-wait-for
        update-types: [version-update:semver-major]
      - dependency-name: '@types/vscode'
        update-types: [version-update:semver-minor]
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'
